name: hashids2
version: 2.0.0
authors: 
- Iwan Sapoetra <isapoetra@gmail.com>
- Olexandr Leuschenko <olexa.le@gmail.com>
description: Hashids is small library to generate YouTube-like ids from numbers. Use Hashids when you do not want to expose your database ids to the user.
homepage: https://github.com/olexale/hashids
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: '>=1.16.5 <2.0.0'
  test_coverage: ^0.5.0
